# -*- coding: utf-8 -*-
"""Crawling Data BigData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwnu7zOobaZO3NXM5_wO5ava_doFEALU
"""

!pip install serpapi
!pip install pandas
!pip install google-search-results

import pandas as pd
from serpapi import GoogleSearch

# Define your parameters for the Google Maps API query
params = {
    "engine": "google_maps",
    "q": "McD",
    "ll": "@-6.905977,107.613144,15.1z",
    "type": "search",
    "api_key": "820cd60161ea8708bd9b9661e81a8e42481158ced8e3415707920913d748c5cf"
}

# Perform the Google Maps API query
search = GoogleSearch(params)
results = search.get_dict()
local_results = results["local_results"]

# Convert the results to a Pandas DataFrame
df = pd.DataFrame(local_results)

# Rename columns if needed
df = df.rename(columns={
    "name": "Name",
    "address": "Address",
    "phone": "Phone",
    "rating": "Rating"
})
print (df)

# Save the DataFrame to a CSV file
csv_filename = "pizza_places.csv"
df.to_csv(csv_filename, index=False)